version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_finance:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=finance-analyser-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data_finance: